### ISSUE TITLE
Plugin is not working with new tns-android version: "2.0.0"

### ISSUE THREAD

**Issue by palpa** [couchbaselabs/nativescript-couchbase#11]
Hi, this is the output I get when I try to compile the demo project:
```
c:\n\nativescript-couchbase\demo>tns run android
Executing before-prepare hook from c:\n\nativescript-couchbase\demo\hooks\before-prepare\nativescript-dev-typescript.js
Found peer TypeScript 1.8.10
app/views/create/create-view-model.ts(1,25): error TS2307: Cannot find module 'nativescript-couchbase'.

app/views/list/list-view-model.ts(1,25): error TS2307: Cannot find module 'nativescript-couchbase'.

Successfully prepared plugin nativescript-couchbase for android.
Successfully prepared plugin tns-core-modules for android.
Project successfully prepared
WARNING: The file: C:\n\nativescript-couchbase\demo\node_modules\nativescript-couchbase\platforms\android\libs\LICENSE.TXT is depricated, you can read more about what will be the expected plugin structure here: https://www.nativescript.org/blog/migrating-n-android-plugins-from-version-1.7-to-2.0

:config phase:  createDefaultIncludeFiles
        +found plugins: nativescript-couchbase

    jcenter()
    flatDir{
        dirs 'libs'
    }
}
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\n\nativescript-couchbase\demo\platforms\android\build.gradle' line: 274

* What went wrong:
A problem occurred evaluating root project 'CouchbaseProject'.
> String index out of range: -1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 11.196 secs
Command c:\n\nativescript-couchbase\demo\platforms\android\gradlew.bat failed with exit code 1
```

**Comment by nraboy** [comment]
Hey @palpa,

I may need to update the README on this one.  Can you try the following if you wish to run the bundled demo?:

```sh
git clone https://github.com/couchbaselabs/nativescript-couchbase
cd nativescript-couchbase
npm run setup
npm run demo.android
```

If you want to know what is happening in the NPM commands, check out the **package.json** file.  Essentially it will download depenencies, build the apps, and run them.  These are not steps that you need to take if you start a project from scratch.

Let me know if those work for you.

Best,

**Comment by palpa** [comment]
Thanks @nraboy for your quick response!
Following your steps it works but I think this is because it maintains the previous tns-android version:
´´´
		"tns-android": {
			"version": "1.7.1"
		}
´´´
Have you tried it after upgrading to tns v2.0.0 in your machine?

I need to use last version in my project as it fixes this issue: https://github.com/NativeScript/nativescript-angular/issues/189, among others!

The issue could be related to a breaking change introduced in the new version:
https://www.nativescript.org/blog/details/migrating-n-android-plugins-from-version-1.7-to-2.0.

Thanks!

**Comment by bradmartin** [comment]
Same result, confirmed with 2.0.0 core-modules and 2.0.0 platform.

**Comment by NathanWalker** [comment]
We should make those changes in the migration guide (https://www.nativescript.org/blog/details/migrating-n-android-plugins-from-version-1.7-to-2.0) mentioned above as well as bump these versions to 2.0.0 and republish?
https://github.com/couchbaselabs/nativescript-couchbase/blob/master/package.json#L8-L9
https://github.com/couchbaselabs/nativescript-couchbase/blob/master/package.json#L33
I'll be upgrading an app which uses this plugin today and will see what I get as well.

**Comment by nraboy** [comment]
I am able to reproduce the issue.  I looked at the following resources:

https://github.com/NativeScript/android-runtime/issues/369
https://www.nativescript.org/blog/details/migrating-n-android-plugins-from-version-1.7-to-2.0
http://pstaev.blogspot.com/2016/03/the-dreaded-nativescript-20-android.html

I am now pretty stumped on how to fix this problem.  All the resources heavily discuss the Android manifest file which this plugin does not have.

Pulling @tjvantoll @PeterStaev and @EddyVerbruggen in to see if they have any ideas.

**Comment by nraboy** [comment]
This issue was fixed in commit https://github.com/couchbaselabs/nativescript-couchbase/commit/9e91f7dcf7ef831a52835cc9a3658421a8408bf7 thanks to @NathanaelA.

However TNS is parsing gradle files, it isn't quite correct in 2.0.0.  It is expecting spaces between brackets in the gradle file.  Not sure Telerik's long term plan on this, but for 2.0.0 this now works.
